# Build from minimal image for speed and security
FROM python:3.10.2-slim-bullseye

ENV WORKDIR=/code
ENV USER=code
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR $WORKDIR

COPY ./requirements.txt $WORKDIR
RUN pip install --upgrade pip && \ 
    pip install -r requirements.txt && \
    adduser --system --group $USER && \
    chown -R $USER:$USER $WORKDIR

COPY ./app/backend $WORKDIR
USER $USER